import pygame 
pygame.init()
#dungeon tile sheet 32*32 they say

class SpriteSheet:
	'''Creating a SpriteSheet for the player/enemy/object !!!!'''
	def __init__(self, image):
		self.sheet = image

	def get_image(self, frame_width,frame_height, width, height, scale, color):
		image = pygame.Surface((width,height)).convert_alpha()
		image.blit(self.sheet,(0,0),((frame_width * width),(frame_height * height),width, height))
		image = pygame.transform.scale(image, (width * scale, height * scale))
		image.set_colorkey(color)
		return image

	#	Constant Variables
#BLACK 		 = (0,0,0)
#SPR_S_WIDTH  = 64
#SPR_S_HEIGHT = 64
#SPR_C_WIDTH  = 39
#SPR_C_HEIGHT = 39
#SPR_D_WIDTH  = 128
#SPR_D_HEIGHT = 128
#BG_SIZE 	 = 512
#WALL_SIZE    = 30
#WALL_WIDTH	 = 134
#BG_IMG_STONE = pygame.image.load(r"images/stone.png").convert()
#
##	Sprite Sheets
#SPR_S_P_LOAD = pygame.image.load(r"images/player_sheet.png").convert_alpha()
#SPR_S_E_LOAD = pygame.image.load(r"images/enemy.png").convert_alpha()
#SPR_S_C_LOAD = pygame.image.load(r"images/chest.png").convert_alpha()
#SPR_S_D_LOAD = pygame.image.load(r"images/Dungeon_Tileset.png").convert_alpha()
#SPR_S_PLAYER = SpriteSheet(SPR_S_P_LOAD)
#SPR_S_ENEMY  = SpriteSheet(SPR_S_E_LOAD)
#SPR_S_CHEST  = SpriteSheet(SPR_S_C_LOAD)
#SPR_S_DUNGEON= SpriteSheet(SPR_S_D_LOAD)
#
##				global vars
#frame_player_000			= SPR_S_PLAYER.get_image( 0, 0, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_enemy_000 			= SPR_S_ENEMY.get_image( 0, 0, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_chest_052 			= SPR_S_CHEST.get_image( 2, 5, SPR_C_WIDTH, SPR_C_HEIGHT, 1.1, BLACK)
#frame_dungeon_sqrwall 		= SPR_S_DUNGEON.get_image( 0, 0, 90, 125, 1.1, BLACK)
#frame_dungeon_linewall_up 	= SPR_S_DUNGEON.get_image( 5, 1, 65, 60, 1.5, BLACK)
#frame_dungeon_linewall_down = SPR_S_DUNGEON.get_image( 5, 1, 65, 60, 1.5, BLACK)


#frame_000 = SPR_S_PLAYER.get_image( 0, 0, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_001 = SPR_S_PLAYER.get_image( 1, 0, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_002 = SPR_S_PLAYER.get_image( 2, 0, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK) 
#frame_003 = SPR_S_PLAYER.get_image( 3, 0, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_004 = SPR_S_PLAYER.get_image( 4, 0, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_005 = SPR_S_PLAYER.get_image( 5, 0, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_006 = SPR_S_PLAYER.get_image( 6, 0, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_108 = SPR_S_PLAYER.get_image( 8, 10, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#    #	row 1
#frame_010 = SPR_S_PLAYER.get_image( 0, 1, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_011 = SPR_S_PLAYER.get_image( 1, 1, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_012 = SPR_S_PLAYER.get_image( 2, 1, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_013 = SPR_S_PLAYER.get_image( 3, 1, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_014 = SPR_S_PLAYER.get_image( 4, 1, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_015 = SPR_S_PLAYER.get_image( 5, 1, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_016 = SPR_S_PLAYER.get_image( 6, 1, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 2
#frame_020 = SPR_S_PLAYER.get_image( 0, 2, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_021 = SPR_S_PLAYER.get_image( 1, 2, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_022 = SPR_S_PLAYER.get_image( 2, 2, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_023 = SPR_S_PLAYER.get_image( 3, 2, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_024 = SPR_S_PLAYER.get_image( 4, 2, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_025 = SPR_S_PLAYER.get_image( 5, 2, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_026 = SPR_S_PLAYER.get_image( 6, 2, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 3
#frame_030 = SPR_S_PLAYER.get_image( 0, 3, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_031 = SPR_S_PLAYER.get_image( 1, 3, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_032 = SPR_S_PLAYER.get_image( 2, 3, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_033 = SPR_S_PLAYER.get_image( 3, 3, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_034 = SPR_S_PLAYER.get_image( 4, 3, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_035 = SPR_S_PLAYER.get_image( 5, 3, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_036 = SPR_S_PLAYER.get_image( 6, 3, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 4
#frame_040 = SPR_S_PLAYER.get_image( 0, 4, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_041 = SPR_S_PLAYER.get_image( 1, 4, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_042 = SPR_S_PLAYER.get_image( 2, 4, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_043 = SPR_S_PLAYER.get_image( 3, 4, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_044 = SPR_S_PLAYER.get_image( 4, 4, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_045 = SPR_S_PLAYER.get_image( 5, 4, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_046 = SPR_S_PLAYER.get_image( 6, 4, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_047 = SPR_S_PLAYER.get_image( 7, 4, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 5
#frame_050 = SPR_S_PLAYER.get_image( 0, 5, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_051 = SPR_S_PLAYER.get_image( 1, 5, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_052 = SPR_S_PLAYER.get_image( 2, 5, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_053 = SPR_S_PLAYER.get_image( 3, 5, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_054 = SPR_S_PLAYER.get_image( 4, 5, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_055 = SPR_S_PLAYER.get_image( 5, 5, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_056 = SPR_S_PLAYER.get_image( 6, 5, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_057 = SPR_S_PLAYER.get_image( 7, 5, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 6
#frame_060 = SPR_S_PLAYER.get_image( 0, 6, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_061 = SPR_S_PLAYER.get_image( 1, 6, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_062 = SPR_S_PLAYER.get_image( 2, 6, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_063 = SPR_S_PLAYER.get_image( 3, 6, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_064 = SPR_S_PLAYER.get_image( 4, 6, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_065 = SPR_S_PLAYER.get_image( 5, 6, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_066 = SPR_S_PLAYER.get_image( 6, 6, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_067 = SPR_S_PLAYER.get_image( 7, 6, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 7
#frame_070 = SPR_S_PLAYER.get_image( 0, 7, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_071 = SPR_S_PLAYER.get_image( 1, 7, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_072 = SPR_S_PLAYER.get_image( 2, 7, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_073 = SPR_S_PLAYER.get_image( 3, 7, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_074 = SPR_S_PLAYER.get_image( 4, 7, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_075 = SPR_S_PLAYER.get_image( 5, 7, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_076 = SPR_S_PLAYER.get_image( 6, 7, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_077 = SPR_S_PLAYER.get_image( 7, 7, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 8
#frame_080 = SPR_S_PLAYER.get_image( 0, 8, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_081 = SPR_S_PLAYER.get_image( 1, 8, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_082 = SPR_S_PLAYER.get_image( 2, 8, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_083 = SPR_S_PLAYER.get_image( 3, 8, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_084 = SPR_S_PLAYER.get_image( 4, 8, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_085 = SPR_S_PLAYER.get_image( 5, 8, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_086 = SPR_S_PLAYER.get_image( 6, 8, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_087 = SPR_S_PLAYER.get_image( 7, 8, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_088 = SPR_S_PLAYER.get_image( 8, 8, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 9
#frame_090 = SPR_S_PLAYER.get_image( 0, 9, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_091 = SPR_S_PLAYER.get_image( 1, 9, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_092 = SPR_S_PLAYER.get_image( 2, 9, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_093 = SPR_S_PLAYER.get_image( 3, 9, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_094 = SPR_S_PLAYER.get_image( 4, 9, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_095 = SPR_S_PLAYER.get_image( 5, 9, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_096 = SPR_S_PLAYER.get_image( 6, 9, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_097 = SPR_S_PLAYER.get_image( 7, 9, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_098 = SPR_S_PLAYER.get_image( 8, 9, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 10
#frame_100 = SPR_S_PLAYER.get_image( 0, 10, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_101 = SPR_S_PLAYER.get_image( 1, 10, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_102 = SPR_S_PLAYER.get_image( 2, 10, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_103 = SPR_S_PLAYER.get_image( 3, 10, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_104 = SPR_S_PLAYER.get_image( 4, 10, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_105 = SPR_S_PLAYER.get_image( 5, 10, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_106 = SPR_S_PLAYER.get_image( 6, 10, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_107 = SPR_S_PLAYER.get_image( 7, 10, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_108 = SPR_S_PLAYER.get_image( 8, 10, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 11
#frame_110 = SPR_S_PLAYER.get_image( 0, 11, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_111 = SPR_S_PLAYER.get_image( 1, 11, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_112 = SPR_S_PLAYER.get_image( 2, 11, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_113 = SPR_S_PLAYER.get_image( 3, 11, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_114 = SPR_S_PLAYER.get_image( 4, 11, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_115 = SPR_S_PLAYER.get_image( 5, 11, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_116 = SPR_S_PLAYER.get_image( 6, 11, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_117 = SPR_S_PLAYER.get_image( 7, 11, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_118 = SPR_S_PLAYER.get_image( 8, 11, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 12
#frame_120 = SPR_S_PLAYER.get_image( 0, 12, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_121 = SPR_S_PLAYER.get_image( 1, 12, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_122 = SPR_S_PLAYER.get_image( 2, 12, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_123 = SPR_S_PLAYER.get_image( 3, 12, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_124 = SPR_S_PLAYER.get_image( 4, 12, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_125 = SPR_S_PLAYER.get_image( 5, 12, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_126 = SPR_S_PLAYER.get_image( 6, 12, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 13
#frame_130 = SPR_S_PLAYER.get_image( 0, 13, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_131 = SPR_S_PLAYER.get_image( 1, 13, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_132 = SPR_S_PLAYER.get_image( 2, 13, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_133 = SPR_S_PLAYER.get_image( 3, 13, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_134 = SPR_S_PLAYER.get_image( 4, 13, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_135 = SPR_S_PLAYER.get_image( 5, 13, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_136 = SPR_S_PLAYER.get_image( 6, 13, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 14
#frame_140 = SPR_S_PLAYER.get_image( 0, 14, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_141 = SPR_S_PLAYER.get_image( 1, 14, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_142 = SPR_S_PLAYER.get_image( 2, 14, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_143 = SPR_S_PLAYER.get_image( 3, 14, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_144 = SPR_S_PLAYER.get_image( 4, 14, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_145 = SPR_S_PLAYER.get_image( 5, 14, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_146 = SPR_S_PLAYER.get_image( 6, 14, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 15
#frame_150 = SPR_S_PLAYER.get_image( 0, 15, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_151 = SPR_S_PLAYER.get_image( 1, 15, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_152 = SPR_S_PLAYER.get_image( 2, 15, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_153 = SPR_S_PLAYER.get_image( 3, 15, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_154 = SPR_S_PLAYER.get_image( 4, 15, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_155 = SPR_S_PLAYER.get_image( 5, 15, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_156 = SPR_S_PLAYER.get_image( 6, 15, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 16
#frame_160 = SPR_S_PLAYER.get_image( 0, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_161 = SPR_S_PLAYER.get_image( 1, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_162 = SPR_S_PLAYER.get_image( 2, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_163 = SPR_S_PLAYER.get_image( 3, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_164 = SPR_S_PLAYER.get_image( 4, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_165 = SPR_S_PLAYER.get_image( 5, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_166 = SPR_S_PLAYER.get_image( 6, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_167 = SPR_S_PLAYER.get_image( 7, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_168 = SPR_S_PLAYER.get_image( 8, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_169 = SPR_S_PLAYER.get_image( 9, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1610 = SPR_S_PLAYER.get_image( 10, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1611 = SPR_S_PLAYER.get_image( 11, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1612 = SPR_S_PLAYER.get_image( 12, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1613 = SPR_S_PLAYER.get_image( 13, 16, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 17
#frame_170 = SPR_S_PLAYER.get_image( 0, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_171 = SPR_S_PLAYER.get_image( 1, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_172 = SPR_S_PLAYER.get_image( 2, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_173 = SPR_S_PLAYER.get_image( 3, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_174 = SPR_S_PLAYER.get_image( 4, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_175 = SPR_S_PLAYER.get_image( 5, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_176 = SPR_S_PLAYER.get_image( 6, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_177 = SPR_S_PLAYER.get_image( 7, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_178 = SPR_S_PLAYER.get_image( 8, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_179 = SPR_S_PLAYER.get_image( 9, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1710 = SPR_S_PLAYER.get_image( 10, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1711 = SPR_S_PLAYER.get_image( 11, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1712 = SPR_S_PLAYER.get_image( 12, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1713 = SPR_S_PLAYER.get_image( 13, 17, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 18
#frame_180 = SPR_S_PLAYER.get_image( 0, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_181 = SPR_S_PLAYER.get_image( 1, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_182 = SPR_S_PLAYER.get_image( 2, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_183 = SPR_S_PLAYER.get_image( 3, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_184 = SPR_S_PLAYER.get_image( 4, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_185 = SPR_S_PLAYER.get_image( 5, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_186 = SPR_S_PLAYER.get_image( 6, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_187 = SPR_S_PLAYER.get_image( 7, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_188 = SPR_S_PLAYER.get_image( 8, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_189 = SPR_S_PLAYER.get_image( 9, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1810 = SPR_S_PLAYER.get_image( 10, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1811 = SPR_S_PLAYER.get_image( 11, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1812 = SPR_S_PLAYER.get_image( 12, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1813 = SPR_S_PLAYER.get_image( 13, 18, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 19
#frame_190 = SPR_S_PLAYER.get_image( 0, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_191 = SPR_S_PLAYER.get_image( 1, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_192 = SPR_S_PLAYER.get_image( 2, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_193 = SPR_S_PLAYER.get_image( 3, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_194 = SPR_S_PLAYER.get_image( 4, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_195 = SPR_S_PLAYER.get_image( 5, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_196 = SPR_S_PLAYER.get_image( 6, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_197 = SPR_S_PLAYER.get_image( 7, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_198 = SPR_S_PLAYER.get_image( 8, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_199 = SPR_S_PLAYER.get_image( 9, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1910 = SPR_S_PLAYER.get_image( 10, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1911 = SPR_S_PLAYER.get_image( 11, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1912 = SPR_S_PLAYER.get_image( 12, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_1913 = SPR_S_PLAYER.get_image( 13, 19, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#	#	row 20
#frame_200 = SPR_S_PLAYER.get_image( 0, 20, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_201 = SPR_S_PLAYER.get_image( 1, 20, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_202 = SPR_S_PLAYER.get_image( 2, 20, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_203 = SPR_S_PLAYER.get_image( 3, 20, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_204 = SPR_S_PLAYER.get_image( 4, 20, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
#frame_205 = SPR_S_PLAYER.get_image( 5, 20, SPR_S_WIDTH, SPR_S_HEIGHT, 1, BLACK)
